apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: json-server
  name: json-server
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: json-server
  type: LoadBalancer
status:
  loadBalancer: {}
